username=input("Please enter your name")
print("Hello",username,"welcome to this class")
print("Hello "+username+ " welcome to this class")
print(f"Hello {username},welcome to this class")
print ("Hello {},welcome to this class".format(username))
#Ways to put a print statement
age=input("Please enter your age")
print("Your age is cofirmed as",age)
print("Your name is",username, "and your age is",age)
print(f"Your name is {username}, and your age is {age}")
print("Your name is {}, and your age is {}".format(username,age))
print("Your name is {1}, and your age is {0}".format(age,username))